version: '3'

services:
  mysqldb:
    image: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Test1234
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Test1234
    ports:
      - 3306:3306

  demo-app:
    image: abdelkal/demo:0.0.1-SNAPSHOT
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb


volumes:
  mysql-db: